app/models.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import nullslast

db = SQLAlchemy()


class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, unique=True, nullable=False)
    description = db.Column(db.String)
    # posts=


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    body = db.Column(db.String, nullable=False)
    # categories=db.
    # tags=db.


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, nullable=False, unique=True)
    email = db.Column(db.String, nullable=False, unique=True)
    __password = db.Column(db.String, nullable=False)
    # posts= db


def configure(app: Flask):
    with app.app_context():
        db.init_app(app)
        db.create_all()

app/__init__.py
from flask import Flask
from flaskext.markdown import Markdown


from . import config, models, blueprints


def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    Markdown(app)
    models.configure(app)
    blueprints.configure(app)

    return app

app/blueprints/__init__.py
from flask import Flask

from .core_bp import core_bp
from .admin_bp import admin_bp
from .blog_bp import blog_bp
from .shop_bp import shop_bp


def configure(app: Flask):
    app.register_blueprint(core_bp)
    app.register_blueprint(admin_bp)
    app.register_blueprint(blog_bp)
    app.register_blueprint(shop_bp)

app/blueprints/admin_bp.py
from flask import Blueprint, redirect, render_template, url_for

from ..utils import posts

admin_bp = Blueprint('admin', import_name=__name__, url_prefix='/admin')

ctx = {"name": "Juacy Willian", "username": "juacywillian"}


@admin_bp.route("/")
def index():
    return render_template('admin/index.html')


@admin_bp.route('/login', methods=['GET', 'POST'])
def login():
    return render_template('admin/login.html')


@admin_bp.route('/logout')
def logout():
    return redirect(url_for('core.index'))


# POST
@admin_bp.route('/post_list', methods=['GET', 'POST'])
def post_list():
    return render_template('admin/post_list.html')


@admin_bp.route('/post_new', methods=['GET', 'POST'])
def post_new():
    return render_template('admin/post_new.html')


@admin_bp.route('/post_edit/<int:id>', methods=['GET', 'POST'])
def post_edit(id: int):
    return render_template('admin/post_edit.html')


@admin_bp.route('/post_remove/<int:id>', methods=['POST'])
def post_remove(id: int):
    return redirect(url_for('admin.post_list'))


# CATEGORY
@admin_bp.route('/category_list', methods=['GET', 'POST'])
def category_list():
    return render_template('admin/category_list.html')


@admin_bp.route('/category_new', methods=['GET', 'POST'])
def category_new():
    return render_template('admin/category_new.html')


@admin_bp.route('/category_edit/<int:id>', methods=['GET', 'POST'])
def category_edit(id: int):
    return render_template('admin/category_edit.html')


@admin_bp.route('/category_remove/<int:id>', methods=['POST'])
def category_remove(id: int):
    return redirect(url_for('admin.category_list'))

app/blueprints/blog_bp.py
from flask import Blueprint, redirect, render_template

from ..utils import posts

blog_bp = Blueprint('blog', import_name=__name__, url_prefix='/blog')

ctx = {"name": "Juacy Willian", "username": "juacywillian"}


@blog_bp.route('/')
def index():
    ctx["posts"] = posts

    return render_template(
        'blog/index.html',
        **ctx,
    )


@blog_bp.route('/view_post/<int:id>')
def view_post(id):
    ctx["post"] = posts[id-1]

    return render_template(
        'blog/view_post.html',
        **ctx
    )

app/blueprints/core_bp.py
from flask import Blueprint, redirect, render_template, url_for

from ..utils import posts

core_bp = Blueprint('core', __name__)


@core_bp.route('/')
def index():
    return redirect(url_for('blog.index'))


@core_bp.route('/about')
def about():
    return render_template('about.html',
                           name="Juacy Willian", username="juacywillian", posts=posts)


@core_bp.route('/portfolio')
def portfolio():
    return render_template('portfolio.html',
                           name="Juacy Willian", username="juacywillian", posts=posts)

app/blueprints/shop_bp.py
from flask import Blueprint, redirect, render_template, url_for

from ..utils import posts

shop_bp = Blueprint('shop', __name__, url_prefix='/shop')


@shop_bp.route('/')
def index():
    return render_template('shop/index.html', )

app/templates/_base.html
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}">
		<title>{% block pagetitle_base %}{% endblock pagetitle_base %}</title>

		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link rel="stylesheet"
					href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap">
		<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&display=swap"
					rel="stylesheet">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.5.0/css/all.min.css">

		<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
	</head>

	<body>
		{% block content_base %}{% endblock content_base %}

		<script src="//code.iconify.design/1/1.0.6/iconify.min.js"></script>
		<script src="{{ url_for('static', filename='js/script.js') }}"></script>
	</body>

</html>

app/templates/blog/_blog.html
{% extends '_base.html' %}

{% block pagetitle_base %}Blog do Will ::
{% block pagetitle %}{% endblock %}
{% endblock pagetitle_base %}

{% block content_base %}

<div class="container">
	<nav class="navbar">
		<a href="{{ url_for('core.index') }}" class="navbar-item">
			<i class="fas fa-home"></i>
			<span class="navbar-item-tag">Blog</span>
		</a>

		<a href="#" class="navbar-item">
			<i class="fas fa-tags"></i>
			<span class="navbar-item-tag">Categorias</span>
		</a>

		<a href="#" class="navbar-item">
			<i class="fas fa-hashtag"></i>
			<span class="navbar-item-tag">Tags</span>
		</a>

		<div class="separador"></div>

		<a href="{{ url_for('shop.index')}}" class="navbar-item">
			<i class="fas fa-store"></i>
			<span class="navbar-item-tag">Loja</span>
		</a>

		<a href="{{ url_for('core.about')}}" class="navbar-item">
			<i class="fas fa-portrait"></i>
			<span class="navbar-item-tag">Sobre mim</span>
		</a>

		<a href="{{ url_for('core.portfolio')}}" class="navbar-item">
			<i class="fas fa-book"></i>
			<span class="navbar-item-tag">Portfolio</span>
		</a>

		<a href="#" class="navbar-item">
			<i class="fas fa-users"></i>
			<span class="navbar-item-tag">Redes Sociais</span>
		</a>

		<a href="#" class="navbar-item">
			<i class="fas fa-cog"></i>
			<span class="navbar-item-tag">Configurações</span>
		</a>
	</nav>

	<div class="main-content">
		<header>
			<div class="cover_container">
				<img src="{{ url_for('static', filename='img/cover.jpg') }}" alt="" class="cover">
				<br>
			</div>

			<img src="{{ url_for('static', filename='img/avatar.jpg' ) }}" alt="" class="avatar">
			<br>
			<h1>{{ name }}</h1>
			<h2 class="subtitle">@{{ username }}</h2>
		</header>

		<main class="content">
			{% block content %}{% endblock %}
		</main>

		<footer></footer>

	</div>
</div>

{% endblock content_base %}

app/templates/blog/article.html
{% extends 'blog/_blog.html' %}

{% block pagetitle %}{{ post.title }}{% endblock pagetitle %}

{% block content %}

<article class="post">
	<header class="post-header">
		<img src="{{ url_for('static', filename='img/avatar.jpg') }}" class="avatar post-avatar">
		<h3 class="post-username">{{ name }}
			<span class="username">@{{ username }} - {{ post.dt }}</span>
		</h3>
	</header>
	<main class="post-content">
		<h4 class="post-title">{{ post.title }}</h4>
		<p class="post-body">{{ post.body|markdown }}</p>
	</main>
	<footer class="post-footer">
		<ul>
			<li>
				<i class="fas fa-comment"></i>
			</li>
			<li>
				<i class="fas fa-heart"></i>
			</li>
			<li>
				<i class="fas fa-share"></i>
			</li>
			<li>
				<i class="fas fa-retweet"></i>
			</li>
		</ul>
	</footer>
</article>

{% endblock %}

app/templates/blog/index.html
{% extends 'blog/_blog.html' %}

{% block pagetitle %}Home{% endblock pagetitle %}

{% block content %}

{% for post in posts %}
<article class="post">
	<header class="post-header">
		<img src="{{ url_for('static', filename='img/avatar.jpg') }}" class="avatar post-avatar">
		<h3 class="post-username">{{ name }}
			<span class="username">@{{ username }} - {{ post.dt }}</span>
		</h3>
	</header>
	<main class="post-content">
		<h4 class="post-title">{{ post.title }}</h4>
		<p class="post-body">{{ post.body.split('\n')[0] }} <a href="{{ url_for('blog.view_post', id=1 ) }}">...more</a></p>
	</main>
	<footer class="post-footer">
		<ul>
			<li>
				<i class="fas fa-comment"></i>
			</li>
			<li>
				<i class="fas fa-heart"></i>
			</li>
			<li>
				<i class="fas fa-share"></i>
			</li>
			<li>
				<i class="fas fa-retweet"></i>
			</li>
		</ul>
	</footer>
</article>
{% endfor %}

{% endblock %}

app/templates/blog/view_post.html
{% extends 'blog/_blog.html' %}

{% block pagetitle %}{{ post.title }}{% endblock pagetitle %}

{% block content %}

<article class="post">
	<header class="post-header">
		<img src="{{ url_for('static', filename='img/avatar.jpg') }}" class="avatar post-avatar">
		<h3 class="post-username">{{ name }}
			<span class="username">@{{ username }} - {{ post.dt }}</span>
		</h3>
	</header>
	<main class="post-content">
		<h4 class="post-title">{{ post.title }}</h4>
		<p class="post-body">{{ post.body|markdown }}</p>
	</main>
	<footer class="post-footer">
		<ul>
			<li>
				<i class="fas fa-comment"></i>
			</li>
			<li>
				<i class="fas fa-heart"></i>
			</li>
			<li>
				<i class="fas fa-share"></i>
			</li>
			<li>
				<i class="fas fa-retweet"></i>
			</li>
		</ul>
	</footer>
</article>

{% endblock %}

app/templates/index.html
{% extends '_blog.html' %}

{% block pagetitle %}Home{% endblock pagetitle %}

{% block content %}

{% for post in posts %}
<article class="post">
  <header class="post-header">
    <img src="{{ url_for('static', filename='img/avatar.jpg') }}" class="avatar post-avatar">
    <h3 class="post-username">{{ name }}
      <span class="username">@{{ username }} - {{ post.dt }}</span>
    </h3>
  </header>
  <main class="post-content">
    <h4 class="post-title">{{ post.title }}</h4>
    <p class="post-body">{{ post.body }}</p>
  </main>
  <footer class="post-footer">
    <ul>
      <li>
        <i class="fas fa-comment"></i>
      </li>
      <li>
        <i class="fas fa-heart"></i>
      </li>
      <li>
        <i class="fas fa-share"></i>
      </li>
      <li>
        <i class="fas fa-retweet"></i>
      </li>
    </ul>
  </footer>
</article>
{% endfor %}

{% endblock %}

app/templates/shop/_shop.html
{% extends '_base.html' %}

{% block pagetitle_base %}Shop{% endblock pagetitle_base %}

{% block content_base %}
<div class="container">
	<header class="flex">
		<input type="text" placeholder="searc" onsubmit="">
		<img src="{{ url_for('static', filename='img/loja-logo2.png') }}" alt="{{ nomedaloja }}" class="cover">

	</header>
	<div class="content flex">
		<aside>
			<div class="widget">
				<h3>Categorias</h3>
				<ul>
					<li>Fones Bluetooth</li>
					<li>Caixas de som bluetooth</li>
					<li>Relógios Quartz</li>
					<li>Relógios Mecanicos</li>
					<li>Mouses sem fio</li>
					<li>Smartwatches</li>
					<li>Carregadores de celular</li>
					<li>Carregadores Portateis</li>
					<li>Smartphones</li>
				</ul>
			</div>
			<div class="widget">
				<h3>Ordenar por</h3>
				<li>Preco asc.</li>
				<li>preco desc.</li>
				<li>mais vendidos</li>
				<li>alfabeto</li>
			</div>
		</aside>
		<main></main>
	</div>
	<footer></footer>
</div>

{% endblock content_base %}

app/templates/shop/index.html
{% extends 'shop/_shop.html' %}

{% block pagetitle %}Home{% endblock pagetitle %}

{% block content %}
{% endblock %}